#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server

grep -v -e "facebook.com" -e "localhost" /etc/hosts > /tmp/hosts
sudo cp /tmp/hosts /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
